repos:
    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.12
      hooks:
        - id: terraform-fmt
        - id: tflint
        - id: shellcheck
        - id: gofmt
        - id: golint
        - id: terragrunt-hclfmt
        - id: markdown-link-check
